### ISSUE TITLE
Question about Signal size and Windows size

### ISSUE THREAD

**Issue by imilk23** [AissamDjahnine/Suppression-of-Acoustic-Noise-in-Speech-Using-Spectral-Subtraction-#1]
Hi @AissamDjahnine 

Thank you for your contribution.

I'm new and I don't have much experience with DSP.

I have questions about this implementation:
1. Why the Nwin=1024? Could I choose another size?
2. Please help me explain the Trames?
 Trames = 1+fix((Length_X-Nwin)/Nhop);

Please respond to me.
Thank you

**Comment by AissamDjahnine** [comment]
Hello @rhett511,

1- Nwin defines the length of each window (a chunk of the signal) and it should be ≪ `len(x)`. You can choose it to be in the range of [128,256,512,1024,2048]. It's important to mention that Nfft is the important parameter here since it is chosen wrt Nwin ( The 'usual' default is to simply use the Nfft length equal to the length of your signal which in this case Nwin).

2- The Trames (in English chunks), cropping the signal x into these chunks using the parameters Nwin, and Nhop. 

* Nwin, as explained above represents the size of the windowed signal that contains 1024 points ( you can choose less or more but be careful about Nhop as well).
* Nhop is the sliding parameter used to extract overlapping windows ( i.e the chunks are not independent, the information contained in the first chunk can be found in the next chunk with an overlap of Nhop). See the example below:

In STFT function:

`win = hamming(Nwin)`
`for i = 0:Trames-1`
      `    xw = x(1+i*Nhop : Nwin+i*Nhop).*win;    % Windowing the signal`  
      `    X = fft(xw, nfft);                      % Compute the STFT of the "Windowed" signal` 
`end`

One can notice that xw ( windowed signal x) , takes in first the points from [1:1024] with another windowing ( hamming, triangular, etc.. you can check why we do this for further information). But in the next iteration, i=1, the windowed signal taken is: from [513,1536]. So it's obvious that these two windowed signals are overlapping which is useful for capturing more frequency information when applying STFT. You can choose to not have overlapping chunks but i doubt if this would be beneficial for this work.

Tell me if this helps, so that I close this issue.

Good luck.

**Comment by imilk23** [comment]
Hi @AissamDjahnine,

It's exactly what I need. I really appreciate your answer.
Thank you for responding to me.

I close this issue with this comment
Thank you.

> Hello @rhett511,
> 
> 1- Nwin defines the length of each window (a chunk of the signal) and it should be ≪ `len(x)`. You can choose it to be in the range of [128,256,512,1024,2048]. It's important to mention that Nfft is the important parameter here since it is chosen wrt Nwin ( The 'usual' default is to simply use the Nfft length equal to the length of your signal which in this case Nwin).
> 
> 2- The Trames (in English chunks), cropping the signal x into these chunks using the parameters Nwin, and Nhop.
> 
> * Nwin, as explained above represents the size of the windowed signal that contains 1024 points ( you can choose less or more but be careful about Nhop as well).
> * Nhop is the sliding parameter used to extract overlapping windows ( i.e the chunks are not independent, the information contained in the first chunk can be found in the next chunk with an overlap of Nhop). See the example below:
> 
> In STFT function:
> 
> `win = hamming(Nwin)`
> `for i = 0:Trames-1`
> ` xw = x(1+i*Nhop : Nwin+i*Nhop).*win; % Windowing the signal`
> ` X = fft(xw, nfft); % Compute the STFT of the "Windowed" signal`
> `end`
> 
> One can notice that xw ( windowed signal x) , takes in first the points from [1:1024] with another windowing ( hamming, triangular, etc.. you can check why we do this for further information). But in the next iteration, i=1, the windowed signal taken is: from [513,1536]. So it's obvious that these two windowed signals are overlapping which is useful for capturing more frequency information when applying STFT. You can choose to not have overlapping chunks but i doubt if this would be beneficial for this work.
> 
> Tell me if this helps, so that I close this issue.
> 
> Good luck.
